// Generated by CoffeeScript 1.6.2
(function() {
  var Thermostat, stat;

  Thermostat = require('./thermostat');

  stat = new Thermostat('ID', 'APIKEY', function(err) {
    return console.log('data loaded from BAYweb');
  });

  stat.mode = 'cool';

  stat.activity = 'occupied';

  stat.setPoint = 76;

  stat.save(function(err) {
    if (err) {
      return console.err(err);
    }
    return console.log('saved!');
  });

}).call(this);
